---
title: "spline demo"
author: "Sherry"
date: "4/8/2021"
output: rmarkdown::github_document
---
```{r}
library(nlstools)
library(dplyr)
library(tidyverse)
library(haven)
library(here)
```

# 0. Read data
```{r}
spdata <- read_sav("spdata.sav")

#Actual and Desired (1)authority, (2)relationships, (3)variety, and (4)autonomy to predict jobsat
spdata1 <- spdata %>% 
  dplyr::select(athh, athw, relh, relw, varh, varw, auth, autw, jobsat) 

psych::describe(spdata1) #Descriptives 
```

# 1.1 Piecewise Regression
$$y = a_0 + a_1x + a_2w + a_3xw + e$$
```{r}
spdata_piece <- spdata1 %>%
  mutate(
         w = if_else(athh > 3, 1, 0), #authority > 3, w = 1
         athh_con = athh - 3
         ) 

model1 <- lm(jobsat~ athh + w + athh:w, data = spdata_piece)
summary(model1)
```

$$
y = a_0 + a_1x + a_2w + a_3xw + e \\
\left\{
  \begin{align}
y &= b_0 + b_1x, \ when \ x \leq 3 \\
y &= b_0 + b_2 + (b_1 + b_3)x, \ when \ x > 3 \\
  \end{align}
\right.
$$
# 1.2 Plotting piecewise 
```{r}
line1 <- function(x) {coef(model1)["(Intercept)"] + coef(model1)["athh"]*x}
line2 <- function(x) {coef(model1)["(Intercept)"] + coef(model1)["w"] +
                     (coef(model1)["athh"] + coef(model1)["athh:w"])*x}

rwrap=function(f,xmin,xmax){ff=function(x){y=f(x);y[x>xmax]=NA;y[x<xmin]=NA;y}}

ggplot(data=spdata_piece,
  aes(x = athh, y = jobsat))+
  theme_bw() +
  scale_y_continuous(limits=c(1, 5))+
  scale_x_continuous(limits = c(1, 5)) + 
  stat_function(fun = rwrap(line1, 1,3), geom="line",col="blue") + 
  stat_function(fun = rwrap(line2, 3,5), geom="line",col="red")
```

## 1.3 Potting piecewise (force the two segments to meet at fixed point c - see Eq.7)
```{r}
model1_con <- lm(jobsat~ athh + athh_con:w, data = spdata_piece)
summary(model1_con)

line1_con <- function(x) {coef(model1_con)["(Intercept)"] + coef(model1_con)["athh"]*x}
line2_con <- function(x) {coef(model1_con)["(Intercept)"] + coef(model1_con)["athh"]*x +
                          coef(model1_con)["athh_con:w"]*(x-3)
                        }

rwrap=function(f,xmin,xmax){ff=function(x){y=f(x);y[x>xmax]=NA;y[x<xmin]=NA;y}}

ggplot(data=spdata_piece,
  aes(x = athh, y = jobsat))+
  theme_bw() +
  scale_y_continuous(limits=c(1, 5))+
  scale_x_continuous(limits = c(1, 5)) + 
  stat_function(fun = rwrap(line1_con, 1,3), geom="line",col="blue") + 
  stat_function(fun = rwrap(line2_con, 3,5), geom="line",col="red")
```


# 2.1 Spline regression
$$
y = b_0 + b_1x + b_2(x-c) +e
$$

$$
\left\{
  \begin{align}
y &= b_0 + b_1x, \ when \ x \leq c \\
y &= b_0 - b_2c + (b_1 + b_2)x, \ when \ x > c \\
  \end{align}
\right.
$$
```{r}
library(nlme)
spline_formula <- as.formula(jobsat ~ (athh <= c)*(b0 + b1*athh) + 
                                      (athh > c)*(b0 - b2*c + (b1 + b2)*athh))

model2 <- nls(spline_formula,
              start = list(b0 = 2.4919, b1 = 0.83799, b2 = -0.61005, c = 3), 
              data = spdata_piece, control = nls.control(maxiter = 100000))
overview(model2)
```

# 2.2 Plotting spline regression
```{r}
line3 <- function(x) {coef(model2)["b0"] + coef(model2)["b1"]*x}
line4 <- function(x) {coef(model2)["b0"] - coef(model2)["b2"]*coef(model2)["c"] +
                     (coef(model2)["b1"] + coef(model2)["b2"])*x}

rwrap=function(f,xmin,xmax){ff=function(x){y=f(x);y[x>xmax]=NA;y[x<xmin]=NA;y}}

ggplot(data=spdata_piece,
  aes(x = athh, y = jobsat))+
  theme_bw() +
  scale_y_continuous(limits=c(1, 5))+
  scale_x_continuous(limits = c(1, 5)) + 
  stat_function(fun = rwrap(line3, 1, coef(model2)["c"]), geom="line",col="blue") + 
  stat_function(fun = rwrap(line4, coef(model2)["c"], 5), geom="line",col="red")
```

Comparison
(a) Piecewise (fixed point = 3)
2.4919 + 0.4014x     (w = 0, x <= 3)
4.3442 + (-0.1186)x  (w = 1, x > 3)

(aa) forcing piecewise to meet at x = 3
2.34376 + 0.48229x (w = 0, x <= 3)
3.70246 + 0.02939x (w = 1, x > 3) 

(b) spline regression (knot = 3.56686)
2.44045  + 0.42633x   (w = 0, x <= 3)
4.540724 + (-0.1625)x (w = 1, x > 3) 